INSERT INTO CAMPANIA
(NOMBRE_CAMPANIA, ID_CARTERA, FECHA_INICIO, ESTADO_CAMPANIA, ID_PERSONAL_REGISTRO)
VALUES
('IVR COBRANZAS EFECTIVA', 1, NOW(), 1, 1);

INSERT INTO CARGA_ARCHIVO
(ID_CAMPANIA, NOMBRE_CLIENTE, NUMERO, MONTO, FECHA_VENCIMIENTO)
VALUES
(1, 'Eder Vela', '51973252592', 500.00, '2025-11-20');


INSERT INTO IVR_PROMPT
(ID_CAMPANIA, NOMBRE, CONTENIDO, VERSION)
VALUES
(
    1,
    'PROMPT EFECTIVA 1',
    'Hola {{NOMBRE}}, le llamamos de C&C Cobranzas Perú. Tiene una deuda de {{MONTO}} soles con vencimiento el {{FVENC}}. Por favor tome nota de esta información.',
    1
);
