 CREATE TABLE CAMPANIA (
    ID_CAMPANIA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_CAMPANIA VARCHAR(100) NOT NULL,
    ID_CARTERA INT NOT NULL,
    FECHA_INICIO DATETIME NOT NULL,
    FECHA_FIN DATETIME,
    ESTADO_CAMPANIA INT DEFAULT 1,
    ID_PERSONAL_REGISTRO INT NOT NULL
);

CREATE TABLE CARGA_ARCHIVO (
    ID_CARGA INT AUTO_INCREMENT PRIMARY KEY,
    ID_CAMPANIA INT NOT NULL,
    NOMBRE_CLIENTE VARCHAR(250),
    NUMERO VARCHAR(20),
    MONTO DECIMAL(10,2),
    FECHA_VENCIMIENTO DATE,
    FOREIGN KEY (ID_CAMPANIA) REFERENCES CAMPANIA(ID_CAMPANIA)
);


CREATE TABLE IVR_PROMPT (
    ID_PROMPT INT AUTO_INCREMENT PRIMARY KEY,
    ID_CAMPANIA INT NOT NULL,
    NOMBRE VARCHAR(150),
    CONTENIDO TEXT NOT NULL,
    VERSION INT DEFAULT 1,
    FECHA_REGISTRO DATETIME DEFAULT NOW(),
    FOREIGN KEY (ID_CAMPANIA) REFERENCES CAMPANIA(ID_CAMPANIA)
);


CREATE TABLE CALLBOT_LLAMADA (
    ID_LLAMADA INT AUTO_INCREMENT PRIMARY KEY,
    ID_CARGA INT NOT NULL,
    ID_CAMPANIA INT NOT NULL,
    TELEFONO VARCHAR(20),
    UNIQUEID VARCHAR(50),
    FECHA_LLAMADA DATETIME,
    DURACION INT,
    BILLSEC INT,
    ESTADO_LLAMADA VARCHAR(50),
    RAZON_CORTE VARCHAR(250),
    ARCHIVO_GRABACION VARCHAR(255),
    RESULTADO_AGI TEXT,
    FOREIGN KEY (ID_CARGA) REFERENCES CARGA_ARCHIVO(ID_CARGA),
    FOREIGN KEY (ID_CAMPANIA) REFERENCES CAMPANIA(ID_CAMPANIA)
);
